### ISSUE TITLE
Generate DAG to build ETH proof before epoch.

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/rainbow-bridge#469]
Proofs computed by eth2near relayer uses [ethashproof](https://github.com/nearprotocol/ethashproof). On changes of epoch to compute a new proof, a relevant DAG needs to be constructed and usually this process might take several minutes. When this happens relayer start failing with uninformative errors. 

```
Failed to get or parse block 9559766: SyntaxError: Unexpected end of JSON input
Got and parsed block 9559766 to block 9559766
TypeError: Cannot read property 'elements' of undefined
```

Proposal:
- [ ] If run for the first time and required DAG is not present, start computing it, and wait until it is ready (don't report errors)
- [ ] Compute in separate thread without blocking main process DAG for next epoch, so it is not needed to wait once epoch change happens.
- [ ] Remove old computed DAG from `~/.ethash` once an epoch is in the past. This is relevant since those files are 1GB large.

Notes:
- To compute DAG for epoch `X` call: `eth2near/ethashproof/cmd/cache/cache X`
- Block `X` belongs to epoch `floor(X / 30000)`

**Comment by djsatok** [comment]
@mfornet should this issue be implemented together with #150 ?

**Comment by KaiserKarel** [comment]
I'd like to have a look at this as well. Where in the code is the DAG computed and currently stored?

**Comment by mfornet** [comment]
> I'd like to have a look at this as well. Where in the code is the DAG computed and currently stored?

We are currently using [this fork](https://github.com/nearprotocol/ethashproof) of [ethashproof](https://github.com/tranvictor/ethashproof). (We have had found several bugs in this repository in the past and we are planning to re-implement it in rust. See #150)

The DAG is generated "lazy" [here](https://github.com/near/rainbow-bridge/blob/master/eth2near/eth2near-block-relay/index.js#L165-L178). When calling the command `/eth2near/ethashproof/cmd/relayer/relayer <block>` it computes the DAG if it doesn't exist, but this process can be very slow, and that is the main point of this issue. There is also another program (`/eth2near/ethashproof/cmd/cache/cache <epoch>`) that computes the DAG for a given epoch before hand.

It is stored in its default location: `~/.ethash`

**Comment by mfornet** [comment]
Recently ropsten bridge eth2near relayer stopped working because it couldn't generate the DAG information from a new epoch due to full disk. The reason for this was that each DAG file size is ~3Gb, and we are not removing old files.
