### ISSUE TITLE
Provide a way to check if a proof was already used.

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/rainbow-bridge#571]
Right now there is no simple way to check if a proof to unlock some tokens was already used (both on Near and Ethereum sides). This is more relevant now that we are planning several relayers to submit tx on behalf of the users. Having this functionality can have a positive impact on frontend UX, since it frontend will be able to determine if the proof was used, and update its state with this info.

### How to do it

Option 1. Using NEAR-Indexer: Create a table with all proofs and query whether this proofs is already in the table. This is probably a convoluted centralised solution.

Option 2. Create view functions in both contracts that allows accessing this information.

**Comment by sept-en** [comment]
Option 2 has been implemented some time ago already.
