### ISSUE TITLE
Near2Eth relayer: `Returned error: exceeds block gas limit`

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/rainbow-bridge#582]
Near2Eth Relayer was using 3,000,000 gas as default to submit blocks. However, after some point, it started failling with:

```
Returned error: exceeds block gas limit
```

You can see last successful tx [here](https://ropsten.etherscan.io/tx/0xa35ebaf979395b61d36b9b27e5f01334f5713b887cf6e11032deb850177b6f69).

If set up gas to 1,500,000 it fails in the same way, and if set to 1,000,000 it fails with Out of Gas. See [here](https://ropsten.etherscan.io/tx/0x65dd28489047b2ea23f63ba0685957e0f6419729cc8a938b1a7f29db67c813db).

**Comment by mfornet** [comment]
The problem is that block gas limit is too small [1.4M](https://ropsten.etherscan.io/block/10233924), while our tx are using more gas in some cases.

**Comment by 0x3bfc** [comment]
we can use the following function to detect the gas price 

```javascript 
export async function getFairGasPrice(web3: Web3): Promise<string> {
  const x = new BigNumber(await web3.eth.getGasPrice())
  return x.multipliedBy(1.05).integerValue(BigNumber.ROUND_DOWN).toString(10)
}
```

**Comment by mfornet** [comment]
> we can use the following function to detect the gas price

The problem is not the gas price, but the gas limit

**Comment by mfornet** [comment]
Solved, waiting for ropsten to normalise gas limit.
