### ISSUE TITLE
Near2Eth Relayer Error: Transaction has been reverted by the EVM

### ISSUE THREAD

**Issue by idirall22** [aurora-is-near/rainbow-bridge#594]
When I run the bridge locally there is an issue with the Near2Ether relayer that keeps restarting and return this error:
Error: Transaction has been reverted by the EVM
![a](https://user-images.githubusercontent.com/26064387/122756896-e4c16280-d28e-11eb-9b77-36404025ef74.PNG)
![b](https://user-images.githubusercontent.com/26064387/122756908-e8ed8000-d28e-11eb-9327-440babb4a7c2.PNG)
![c](https://user-images.githubusercontent.com/26064387/122756920-ec810700-d28e-11eb-8ba5-72577f5128c4.PNG)

I investigated inside the code and it looks like this [this](https://github.com/aurora-is-near/rainbow-bridge/blob/master/near2eth/near2eth-block-relay/index.js#L101 ) initWithValidators is the source of the error.

**Comment by mfornet** [comment]
Interesting. It seems to be `initWithValidators`, but if that is the case logs are out of order (this may happen due to async nature of this code). Can you describe how are you initialising the bridge?

**Comment by idirall22** [comment]
I followed the instruction inside the README 
- yarn install
- cli/index.js clean
- cli/index.js prepare --core-src ${HOME}/Desktop/core
- cli/index.js start near-node
- cli/index.js start ganache
- cd contracts/eth/nearbridge/ && yarn && yarn build
- cd contracts/eth/nearprover/ && yarn && yarn build
- cli/index.js init-near-contracts
- cli/index.js init-eth-ed25519
- cli/index.js init-eth-client --eth-client-lock-eth-amount 1000 --eth-client-lock-duration 10
- cli/index.js init-eth-prover
- cli/index.js init-eth-erc20
- cli/index.js init-eth-locker
- cli/index.js init-near-token-factory
- cli/index.js start eth2near-relay
- cli/index.js start near2eth-relay --eth-master-sk 0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501201
- cli/index.js start bridge-watchdog --eth-master-sk 0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501202
- pm2 logs

**Comment by mfornet** [comment]
@idirall22 did you manage to fix this issue. I can't reproduce it locally.

**Comment by idirall22** [comment]
Hey @mfornet No I did not investigate it, but I run the same commands and above one after one but still get the same error. If I have some time I'll investigate more.

**Comment by idirall22** [comment]
https://testnet.bscscan.com/tx/0x7f657e99492149048a6d7e07397d23b2fd68f0c5d4e1d49e4f42dbb286a4cebb

**Comment by idirall22** [comment]
The issue is with the near2eth relayer which inits the BridgeContract on eth with an empty object.
We fixed this issue on the BSC branch
https://github.com/aurora-is-near/rainbow-bridge/blob/bsc/near2eth/near2eth-block-relay/index.js#L73
