### ISSUE TITLE
[Aurora Testnet Faucet] CORS error

### ISSUE THREAD

**Issue by danielwpz** [aurora-is-near/rainbow-bridge#609]
when I tried to use the aurora faucet to get some test tokens, I got an network error :

> Access to fetch at 'https://faucet.testnet.aurora.dev/v0/request' from origin 'https://testnet.aurora.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Seems the webserver of faucet wasn't configured correctly with CORS policy?
I'm willing to help patching the server if someone can kindly show me which github repo it is.

**Comment by think-in-universe** [comment]
Faucet is working now in our test today. Thanks!
