### ISSUE TITLE
initialize the near client "RlpIsTooShort"

### ISSUE THREAD

**Issue by idirall22** [aurora-is-near/rainbow-bridge#616]
Hello
### Error
I'm trying to run the bridge locally using the main branch, but I have an error related to block header RLP:

![gggg](https://user-images.githubusercontent.com/26064387/128828907-5409e69f-6d14-4244-a2d7-520f22aca796.PNG)

### Actions
- yarn
- yarn install
- cd contracts/eth/nearbridge/ && yarn && yarn build
- cd contracts/eth/nearprover/ && yarn && yarn build
- cli/index.js clean
- cli/index.js prepare
- cli/index.js start near-node
- cli/index.js start ganache
- cli/index.js init-near-contracts
- cli/index.js init-near-contracts  <---- ERROR

tests fail
![Capture](https://user-images.githubusercontent.com/26064387/130420415-6b35e02d-2792-4618-bd1b-3f0c827bfc38.PNG)

**Comment by sept-en** [comment]
Fixed in #636
