### ISSUE TITLE
Aurora Testnet Bridge should have moved to Goerli

### ISSUE THREAD

**Issue by think-in-universe** [aurora-is-near/rainbow-bridge#626]
The testnet bridge (https://testnet.aurora.dev/bridge) should have moved from **Ropsten** to **Goerli**, but the title ("Connected to Ropsten Testnet") here doesn't change. 

![image](https://user-images.githubusercontent.com/46699230/131480973-38ee4e7a-3288-496a-8dcc-3aa9e27b5b86.png)

**Comment by paouvrard** [comment]
Thanks for noticing, it is now fixed.
