### ISSUE TITLE
Update Near Light Client to support new ValidatorStake

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/rainbow-bridge#644]
[ProtocolFeatures::BlockHeaderV3](https://github.com/near/nearcore/blob/master/core/primitives/src/version.rs#L174) on NEAR will change the way [next block producers are serialised](https://github.com/near/nearcore/blob/351519344cbe205a255dd6c1c2f0ae4a3f7c84d7/chain/chain/src/chain.rs#L506-L520). Notice the difference between [ValidatorStakeV1](https://github.com/near/nearcore/blob/52e822d08c514b1f846037e5e40032f2f2bbaee7/core/primitives/src/types.rs#L683-L690) and [ValidatorStakeV2](https://github.com/near/nearcore/blob/52e822d08c514b1f846037e5e40032f2f2bbaee7/core/primitives/src/types.rs#L483-L493). (One byte at the end indicating if it is a Chunk Producer or not).

Because of this the NearLightClient implementation on Ethereum should be updated.
- The [hash computation](https://github.com/aurora-is-near/rainbow-bridge/blob/63fb73ba3c3ced07b57c3040a5c6cdaff5d0f255/contracts/eth/nearbridge/contracts/NearDecoder.sol#L64) is correct and requires no changes, since it takes into account all the raw data.
- The way [block producer are deserialised](https://github.com/aurora-is-near/rainbow-bridge/blob/63fb73ba3c3ced07b57c3040a5c6cdaff5d0f255/contracts/eth/nearbridge/contracts/NearDecoder.sol#L35-L39) requires to be updated, taking into account the new field (one byte). The content of this byte can be ignored in the same way the account id is ignored (only used to compute the hash).

If the bridge is updated before this feature becomes live, we must make sure the bridge light client is aware about the protocol version, and deserialise each value according to the protocol version. Right now I'm investigating if this is possible.

---

Since only the Light Client needs to be upgraded, this can be done safely, and after the deployment is done properly, then the Prover can point to the new Light Client.

**Comment by EgorKulikov** [comment]
Please note that ValidatorStakeV2 would not be released with this update, we will just update from current struct to enum, which has only one variant at the moment

**Comment by sept-en** [comment]
Closed in #646
