### ISSUE TITLE
BSC Fail to validate the signer and difficult

### ISSUE THREAD

**Issue by idirall22** [aurora-is-near/rainbow-bridge#661]
Hello Guys!

We started the bsc bridge on the testnet, everything was good we validated more than 50k BSC blocks. But when we reached the epoch 15180200 the bsc consensus failed to validate the headers [here](https://github.com/aurora-is-near/rainbow-bridge/blob/bsc/contracts/near/eth-client/src/lib.rs#L609)

After debugging, we observed that only the first 4 blocks are not valid [ 15180200, 15180201, 15180202, 15180203 ], but the next epochs are all valid.

Also, we observed that this happens when the validator set increases:
- epoch 15180000  => 6 validators
- epoch 15180200  => 7 validators
There is no issue when the validator set decreases.
**The inturn is not equal to the block signer and the difficulty also is not valid**.

We believe that for testnet they are ignoring the signer and difficulty checks see [here](https://github.com/binance-chain/bsc/blob/master/consensus/parlia/parlia.go#L215)

bsc consensus [here](https://github.com/binance-chain/bsc/blob/master/consensus/parlia/parlia.go#L587).

**Comment by sept-en** [comment]
@idirall22 we can close it because of #662, right?

**Comment by idirall22** [comment]
@sept-en
No this is not related to epoch block #662, it's related to the block signer and difficulty, which is not yet fixed.
