### ISSUE TITLE
BSC: undetermined behavior of adding blocks

### ISSUE THREAD

**Issue by karim-en** [aurora-is-near/rainbow-bridge#671]
At this [line](https://github.com/aurora-is-near/rainbow-bridge/blob/bsc/contracts/near/eth-client/src/lib.rs#L474 ) we can see that adding blocks from scratch is valid behavior, but the test that adds the first 10 blocks is [failing](https://github.com/aurora-is-near/rainbow-bridge/pull/670/files#diff-348fbb1b669978271886429d8eccbca0915a8689b504f19de4aedc5c1641453cR579)

**Comment by karim-en** [comment]
@idirall22 FYI

**Comment by idirall22** [comment]
Hey @karim-en 
I already opend an issue for this here #661

**Comment by sept-en** [comment]
Fixed in #693
