### ISSUE TITLE
Add manual address for bridging to NEAR

### ISSUE THREAD

**Issue by vwim** [aurora-is-near/rainbow-bridge#700]
Right now the only way to create a wallet on NEAR is via an initial CEX deposit. Consider adding the option to manually insert the initial deposit address so users can create NEAR wallets with the rainbow bridge.

**Comment by mfornet** [comment]
Hi @vwim this is possible, if you send $NEAR directly from Ethereum to NEAR. 

You need to check on NEAR wallet the minimum amount required for the account to become active, which AFAIR is 0.2NEAR.
