### ISSUE TITLE
ERC-721 and ERC-1155 support

### ISSUE THREAD

**Issue by keon** [aurora-is-near/rainbow-bridge#713]
Is there a workstream going on for supporting ERC-721 and ERC-1155 transfers?
I've seen the bounty taken down recently. 
I'd like to work on supporting NFT transfers but lack in context.

ref: https://github.com/near/bounties/issues/29

**Comment by sept-en** [comment]
It's already on the review stage in the separate repository: https://github.com/aurora-is-near/rainbow-non-fungible-token-connector/pull/5
For all NFT-related questions, please post it in that repo.
